- app/controllers/home_controller.rb
- app/views/home/servicestatus.html.erb
- config/application.rb
- config/routes.rb
This adds /servicestatus and /servicestatus.json endpoints. These are useful for conveniently checking the service is OK, monitoring the deployed revision and checking uptime.
> # Add /servicestatus endpoint to allow automated status monitoring.

- config/deploy.rb
This silences a bundler deprecation warning on deployments. This ensures that successful deployments should have no messages on STDERR.
> # Avoid spurious deprecation warnings with capistrano 2 and bundler 2.x

- lib/import/colorectal/providers/london_gosh/london_gosh_handler_colorectal.rb
- test/lib/import/colorectal/providers/london_gosh/london_gosh_handler_colorectal_test.rb
- Fix for varpathclass assigned to only abnormal gene in Gosh (RP4) colorectal records.
- Updated test cases to make assertions not based on logging statements.
Analysts have observed that varpathclass is getting assigned to normal genes , so Fiona has asked to change the code to assign varpathclass only to abnormal genes as being done in Gosh BRCA handler. It resolves  #Planio-33988.
A new assertion has been added to test and also test file is updated to make assertions independent of logging statements.
> Gosh CRC varpathclass assignment , resolves #33988

- lib/import/brca/providers/newcastle/newcastle_handler.rb
- lib/import/colorectal/providers/newcastle/newcastle_handler_colorectal.rb
- test/lib/import/brca/providers/newcastle/newcastle_handler_test.rb
- test/lib/import/colorectal/providers/newcastle/newcastle_handler_colorectal_test.rb
This is to assign variantpath class only to the gene listed in raw['gene'] and not all genes of the record.
These changes are to resolve planio ticket #https://ncr.plan.io/issues/34051
Added new test
> Fix for variantpathclass assignment

- lib/import/helpers/colorectal/providers/rth/constants.rb
- test/lib/import/colorectal/providers/oxford/oxford_handler_colorectal_test.rb
I have amended regex of chromomosomal and codingdnasequence to allow _c.?_ and _Inversion of exon_ to be captured as positive genotype.
Fiona after analysts suggestions has asked that for Oxford colorectal , above cases should be marked as positive. 
More information can be found in planio ticket #34166
Changes in the regex.
Have added test case for above scenario.
> Oxford CRC assign positive test status

- Gemfile.lock
Bump `selenium-webdriver` gem to support Chrome 116.
The `bundle audit` failure is for an independent security issue, that will be addressed in a separate PR.
> # Bump selenium-webdriver to 4.11.0

- config/deploy.rb
This fixes an omission from PR #29, by adding `puma-daemon` to the list of out-of-bundle gems for deployments.
> Update out-of-bundle gems for deployments.

- lib/import/helpers/brca/providers/rvj/rvj_constants.rb
- test/lib/import/brca/providers/bristol/bristol_handler_test.rb
Test status for ‘raw:variantpathclass’ = ‘Benign’ or ‘Likely Benign’, should be 10.
Tests updated and denominators QA approved by Fiona
> Status changes as per varpathclass

- .github/workflows/future_proof.yml
- Gemfile
- Gemfile.lock
- lib/tasks/smoke_test.rake
This PR adds a "Future proof / Ruby 3.0 Smoke Tests" check to GitHub Actions, which ensures that the `data_management_system` code passes basic smoke tests with the latest gemfiles and the latest ruby 3.0.x release.
There's a similar "Future proof / Ruby 3.1 Smoke Tests" check.
We'll need to allow a newer version of the `pg` gem to start supporting Ruby 3.2. We can't do this yet, with our current CentOS 7 application configurations.
> GitHub Actions should test compatibility with newer ruby and gem versions.

- test/test_helper.rb
This removes support for old chrome headless configuration, for chrome < 77 (releases before 2019-09).
> Tests should support latest chrome driver releases

- config/initializers/devise.rb
A running instance of the app experienced clock drift between it's host and the trusted IdP.  The tight default tolerances in the default devise meant this broke SAML response validation when the IdP drifted ahead of the app host.
This PR relaxes the default config which, given the other controls in place in the only known deployment, should be pragmatic and safe
> Tolerate IDP time drift in devise config

- lib/import/brca/scripts/bash/Import_all_brca_interactive.sh
Excluding "other" named files as records from the Newcastle lab where the filename contains the word ‘other’ are not genuine BRCA tests
> exclude other files from newcastle brca

- lib/import/brca/providers/st_george_old/st_george_handler_old.rb
- lib/import/brca/scripts/bash/Import_all_brca_interactive.sh
- test/fixtures/zproviders.yml
- test/lib/import/brca/providers/st_george_old/st_george_handler_old_test.rb
What?
PR to fix issue with running two handlers for one provider (St George's BRCA). 
How ?
Replacing the ebatch registry code and provider code before data is persisted in the database will permit two seperate handlers to be run for the same provider code.
Testing?
Added relevant test case for method.
Anything Else?
> importer fix for old st george hander

- lib/import/colorectal/scripts/bash/Import_all_colorectal_interactive.sh
Removing Lynch script as discussed on yesterday Germline call, so as not to import Lynch data along with Germline data as part of CASREF Refresh.
Lynch data will be imported separately.
> Remove importing script for lynch data

- lib/import/brca/scripts/bash/Import_all_brca_interactive.sh
Updating RQ3 script to exclude Rare files case insensitive mode
While running script for CASREF REFRESH , BRCA Birmingham importer failed for `...2023_Q1 RARE.xlsx.pseudo` which ideally shouldn't have been picked by BRCA handlers.
Ran RQ3 script and now rake doesn't get aborted .
> Updating RQ3 script to exclude Rare files case insensitive mode

- lib/import/colorectal/scripts/bash/Import_all_colorectal_interactive.sh
RCU colorectal script should also import one wrongly labelled BRCA file.
Its a mixed file to be imported by both BRCA and CRC handler.
Added to RCU script
> updated rcu script

- lib/import/brca/scripts/bash/Import_all_brca_interactive.sh
Removing "TP53" files from being processed via BRCA old importer
Requirement to not parse filenames that contain 'TP53' in their title.
Have checked not parsing 2 TP53 files now.
> Removing 'TP53' files

- lib/import/brca/providers/oxford/oxford_handler.rb
- lib/import/helpers/brca/providers/rth/constants.rb
- test/lib/import/brca/providers/oxford/oxford_handler_test.rb
During CASREF QA , Fiona and Jo have detected 5 incompatible teststatus and varpath class records for OXFORD (RTH) - 
- 1 record where teststatus is null and varpathclass is 4
- 1 record where teststatus is null and varpathclass is 5
- 3 records where teststatus is null and varpathclass is 3
Regex wasn't capturing the variants for these and hence not calling method to allocate the teststatus.
Fixed the regex , also corrected my understanding with help from @NImeson of cdna variants which were rightly constructed but my code was putting them in exemptions considering malformed.
Added test for impacted cases which are now rightly getting assigned teststatus along with varpathclass.
Also ran importer locally and could confirm counts are as expected and also query brings desired result - 
``` …
```
> Fixed regex to capture variants to avoid incompatible varpathclass and teststatus

- lib/import/colorectal/core/genocolorectal.rb
- lib/import/colorectal/providers/leeds/leeds_handler_colorectal.rb
- lib/import/helpers/colorectal/providers/rr8/constants.rb
- test/lib/import/colorectal/providers/leeds/leeds_handler_colorectal_test.rb
During last CASREF Refresh , Fiona identified missing SRIs from MMR files that didn't get imported in database.
The records didn't have any gene info and hence got skipped from getting persisted in db.
Fiona has provided new rule to get genes based on Moleculartestingtype if couldn't determine from report or genotype. Also if no gene is present then record must get persisted in DB without gene info.
Test have been added and ran importer locally to see missing SRIs are now getting persisted.
> Missing SRIs fix

- app/models/pseudo/death.rb
- db/schema.rb
- db/structure.sql
- lib/export/cancer_death_common.rb
- lib/export/death_file.rb
- test/integration/project_amendments_test.rb
- test/integration/project_assignments_test.rb
- test/integration_test_helper.rb
- test/lib/export/cancer_death_common_test.rb
- test/lib/export/death_file_test.rb
- test/models/pseudo/death_test.rb
This PR adds interim support for cause of death 1d exports, until the export formats can be changed. [NDRS2-2014]
* Cancer death extract should temporarily treat death cause 1d as part of 1c.
The longer-term fix is to change the cancer death extract to add another field for cause of death 1(d). Any affected death records should then be re-extracted.
> Interim support for cause of death 1d exports

- .github/workflows/test.yml
This PR ignores the bootstrap 3 `bundle audit` security warning on the `bootstrap-sass` gem: this is an accepted risk that we plan to fix, but which will need substantial work. Flagging this as an error on every PR is just noise at this point, and could obscure other, new security issues.
> Ignore bootstrap version 3 warning [NDRS2-1676]

- lib/import/colorectal/providers/leeds/leeds_handler_colorectal.rb
We were waiting to hear from lab for gene to be confirmed for one of the missing SRIs from Leeds,(detected during CASREF Refresh) so now it's added in this PR.
Fiona wanted to be sure if the combination of moleculartestingtype and indicationcategory is meant for MLH1 and asked lab to confirm. Today email has been answered by Rachel from Leeds.
Rules have been updated to include above combination to determine gene.
Have run locally and now query return expected result of 3845 -
```
select count(distinct(servicereportidentifier)) from restricted_results_all where original_filename like '%MMR%';
count 
-------
3845
(1 row)
```
For reference email dated 22 July 2024 from Fiona "FW: Leeds CRC SRIs" can be seen.
> Added another rule for missing SRI

- config/attribute-map.yml
- config/initializers/devise.rb
The PHE ADFS server now includes blank email addresses for (some?) ex @phe staff. This PR ignores the `emailaddress` SAML field: the `User` object being updated on login, which was causing an error when a blank email address was being applied. Instead, users are identified by the `upn` (which contains their email address).
I've deployed this to the beta site before review, to confirm that it works.
> Allow ADFS login for accounts without a SAML emailaddress

- lib/import/brca/providers/bristol/bristol_handler.rb
Some of the Bristol records were missing ORGANISATIONCODE_TESTRESULT .  More details on Jira #2056
Genotype duplication logic was wrong and rather duplicating a new genotype, it was being created from raw record and hence was loosing on the properties already set.
Logic has been rightly applied for duplicating genotype and also code has been restructured.
```select * from molecular_data where organisationcode_testresult is null;  ``` gives 0 rows now.
> Fixed bug for missing organisational_testresult
